spring:
  application:
    name: Avesena Home Services
  thymeleaf:
    suffix: .html
    cache: false
    enabled: true
    prefix: classpath:/templates/
  security:
    user:
      name: sudeen
      password: 12345
server:
  port: 8081
  servlet:
    context-path: /auth
